language: node_js

node_js :
    - "v8"
    - "v9"

addons:
    postgresql: "9.6"

before_script:
  - psql -f test/createdb.sql -U postgres
  - psql -f test/postgres.sql -U postgres
  - mysql -e 'create database ee_orm_test_mysql;'


sudo: false
